default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: abc_sandbox_development

test:
  <<: *default
  database: abc_sandbox_test

production:
  <<: *default
  database: abc_sandbox_production
